[project]
name = "mlplayground"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "box2d>=2.3.10",
    "glfw>=2.9.0",
    "numpy>=2.3.2",
    "pyglm>=2.8.2",
    "pyopengl>=3.1.10",
]
